name: Publish Package to github
on:
  release:
    types: [published]

#  push:
#    branches: [ main ]

#permissions: read-all|write-all
permissions:
  contents: write

jobs:
  build:

    strategy:
      matrix:
        node-version: [ 18.x ]
        os: [ ubuntu-20.04, windows-latest, macos-latest ]
        include:
          - target: aarch64-apple-darwin
            os: macos-latest

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'
          if: matrix.os == 'windows-latest'
          registry-url: 'https://registry.npm.taobao.org'
#          registry-url: 'https://registry.npmjs.org'
      - if: matrix.os == 'ubuntu-20.04'
        run: |
          sudo apt-get install rpm -y
      - if: matrix.platform == 'macos-latest'
        run: |
          rustup target add aarch64-apple-darwin
      - run: yarn
      - run: yarn build:react
      - run: yarn run publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
