name: Publish Package to github
on:
#  release:
#    types: [published]

  push:
    branches: [ main ]

#permissions: read-all|write-all
permissions:
  contents: write

jobs:
  build:

    strategy:
      matrix:
        include:
          - target: aarch64-apple-darwin
            platform: macos-latest
          - target: x86_64-apple-darwin
            platform: macos-latest
          - target: x86_64-unknown-linux-gnu
            platform: ubuntu-20.04
          - target: x86_64-pc-windows-msvc
            platform: windows-latest

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'yarn'
#          if: matrix.platform == 'windows-latest'
#          registry-url: 'https://registry.npm.taobao.org'
#          registry-url: 'https://registry.npmjs.org'
      - if: matrix.platform == 'ubuntu-20.04'
        run: |
          sudo apt-get install rpm -y
#      - uses: actions/cache@v2
#        with:
#          path: '**/node_modules'
#          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/yarn.lock') }}
      - if: matrix.target == 'aarch64-apple-darwin'
        run: export npm_config_arch=arm64
      - run: yarn
      - run: yarn build:react
      - run: yarn run publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
